#!/bin/bash

#Here I'm storing the hostname in the shortest way to put ir on the variable host
host=$(hostnamectl | grep "Static hostname:" | awk '{ print $3 }')

#CPU info is troed in cpu 
cpu=$(sudo lshw -short | grep processor |  awk '{print $3,$4,$5,$6,$7,$8,$9}' | head -n 1)

#Storing free RAM in variable ram
ram=$(free --mega | grep Mem | awk '{print $2}')

#Same but ip, default gateway, DNS in their variables
ip=$(ip route | head -n 1| awk '{print $9}' )
gateway=$(ip route | head -n 1 | awk '{print $3}')
dns=$(resolvectl | grep "Current DNS" | awk '{print $4}')

#Gathering vendor make and model of display
vendorMake=$(sudo lshw -C display | grep vendor | awk '{print $2}')
vendorModel=$(sudo lshw -C display | grep product | awk '{print $2,$3,$4}')

#Gathering vendor make, model and size of disk
disk=$(lsblk -o NAME,MODEL,SIZE | grep sda | head -n 1 | awk '{print $2,$3,$4,$5}')

#uptime
up=$(uptime | awk '{print $3,$4}' | awk -F, '{print $1}' )



#For process count I will create the command to retrieve all the info in one line but
#I will create another variable to do -1 because the first output will give a headline is not an actual process
processCount=$(ps -A | wc -l)
totalCount=$((processCount - 1))

#load averages
loadAverages=$(uptime | awk '{print $9,$10,$11}')

#local file systems fromat /mount n
fileSystem=$(df -m | grep /dev/sda | awk '{print "Located at",$6,"Mem Av, "$4, "Mb"}')

#UFW status
ufw=$(sudo ufw status | awk '{print $2}')

#Gathering listening ports
listeningPorts=$(ss -tuln | grep LISTEN | awk -F: '{print $2}' | awk '{print $1}' | tr '\n' ' ')

. /etc/os-release

cat <<EOF
System Report for $host generated by $USERNAME, on $(date)

System Information
------------------
OS: $NAME $VERSION
Uptime: $up
CPU: $cpu
RAM: $ram Mb Installed
Disks: $disk
Video: $vendorMake $vendorModel
Host Address: $ip
Gateway IP: $gateway
DNS Server: $dns

System Status
-----------------
Users Logged In: $(users)
Disk Space: $fileSystem
Process Count: $totalCount
Load Averages: $loadAverages
Listening Network Ports: $listeningPorts
UFW Status: $ufw
EOF

