#!/bin/bash

#Here I'm storing the hostname in the shortest way to put ir on the variable host
host=$(hostnamectl | grep "Static hostname:" | awk '{ print $3 }')
#Here I did the same but with the cpu
cpu=$(sudo lshw -short | grep processor |  awk '{print $3,$4,$5,$6,$7,$8,$9}' | head -n 1)
#Same but RAM
ram=$(free --mega | grep Mem | awk '{print $2}')
#Same but ip, default gateway, DNS
ip=$(ip route | head -n 1| awk '{print $9}' )
gateway=$(ip route | head -n 1 | awk '{print $3}')
dns=$(resolvectl | grep "Current DNS" | awk '{print $4}')
#Gatherin vendor make and model
vendorMake=$(sudo lshw -C display | grep vendor | awk '{print $2}')
vendorModel=$(sudo lshw -C display | grep product | awk '{print $2,$3,$4}')

source /etc/os-release

cat <<EOF
System Report for $host generated by $USERNAME, on $(date)

System Information
------------------
OS: $NAME  $VERSION
Uptime: $(uptime | awk '{print $2,$3}' )
CPU: $cpu
RAM: $ram Installed
Disk(s): MAKE AND MODEL AND SIZE FOR ALL INSTALLED DISKS
Video: $vendorMake $vendorModel
Host Address: $ip
Gateway IP: $gateway
DNS Server: $dns


EOF

